# -*- coding: utf-8 -*-
"""Twitter_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmaOs1LUMn1yYfaTsE3yB8JwLwmd6YMq
"""

from google.colab import files
uploaded = files.upload()

{'twitter_data.csv': 1234567}

import os
os.listdir()

import os
os.listdir()

import os
os.listdir()

import pandas as pd

df = pd.read_csv("Twitter_Data.csv")
df.head()

df.info()
df.columns
df['category'].value_counts()

df = df.dropna()

df.isnull().sum()

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=y)
plt.title("Sentiment Distribution in Twitter Data")
plt.show()

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
df = pd.read_csv("Twitter_Data.csv")

# Drop null values
df = df.dropna()

# Features and target
X = df['clean_text']   # change column name if different
y = df['category']

# Convert text into numbers
vectorizer = TfidfVectorizer(stop_words='english')
X_vectorized = vectorizer.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized, y, test_size=0.2, random_state=42
)

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# Sentiment Distribution Graph
sns.countplot(x=y)
plt.title("Sentiment Distribution in Twitter Data")
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()